# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [7]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1,2,4,3])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,3,2],[3,5,2]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1,41,2], [4,2,6]], [[1,3,6], [7,4,5]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [13]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
np.shape(arr1), np.ndim(arr1), type(arr1), np.size(arr1)

((4,), 1, numpy.ndarray, 4)

In [14]:
# Attributes of 2-dimensional array
np.shape(arr2), np.ndim(arr2), type(arr2), np.size(arr2)

((2, 3), 2, numpy.ndarray, 6)

In [15]:
# Attributes of 3-dimensional array
np.shape(arr3), np.ndim(arr3), type(arr3), np.size(arr3)

((2, 2, 3), 3, numpy.ndarray, 12)

In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(arr2)
df

0  1  2
0  1  3  2
1  3  5  2

In [19]:
# Create an array of shape (10, 2) with only ones
ones = np.ones([10,2])
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros([7,2,3])
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [22]:
# Create an array within a range of 0 and 100 with step 3
arr = np.arange(0, 100, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
rand_arr = np.random.randint(0, 10, [7,2])
rand_arr

array([[4, 1],
       [6, 2],
       [8, 9],
       [9, 1],
       [4, 7],
       [3, 6],
       [3, 5]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_floats = np.random.rand(3, 5)
rand_floats

array([[0.97629658, 0.28313173, 0.82166331, 0.67349785, 0.35095147],
       [0.148815  , 0.8609804 , 0.78390004, 0.73247117, 0.5119656 ],
       [0.28380419, 0.74768638, 0.64594747, 0.4554656 , 0.93084983]])

In [31]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.randint(0, 10, [4,6])

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [46]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr_int = np.random.randint(1,10,[3,7])
arr_int
# Find the unique numbers in the array you just created
np.unique(arr_int)

array([1, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# Find the 0'th index of the latest array you created
arr_int[0]

array([1, 5, 5, 7, 9, 9, 3])

In [48]:
# Get the first 2 rows of latest array you created
arr_int[0:2]

array([[1, 5, 5, 7, 9, 9, 3],
       [3, 3, 4, 8, 6, 8, 1]])

In [49]:
# Get the first 2 values of the first 2 rows of the latest array
arr_int[:2,:2]

array([[1, 5],
       [3, 3]])

In [50]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_new = np.random.randint(0,10,[3,5])
arr_ones = np.ones([3,5])

In [52]:
# Add the two arrays together
np.array([arr_new, arr_ones])

array([[[3., 2., 8., 2., 8.],
        [1., 1., 1., 5., 2.],
        [8., 3., 0., 3., 0.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [53]:
# Create another array of ones of shape (5, 3)
arr_ones_new = np.ones([5,3])

In [54]:
# Try add the array of ones and the other most recent array together
np.array([arr_ones, arr_ones_new])

C:\Users\hanse\AppData\Local\Temp\ipykernel_7916\1148481808.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([arr_ones, arr_ones_new])


array([array([[1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1.],
              [1., 1., 1., 1., 1.]]), array([[1., 1., 1.],
                                             [1., 1., 1.],
                                             [1., 1., 1.],
                                             [1., 1., 1.],
                                             [1., 1., 1.]])], dtype=object)

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [56]:
# Create another array of ones of shape (3, 5)
arr_ones_new = np.ones([3,5])

In [57]:
# Subtract the new array of ones from the other most recent array
arr_ones - arr_ones_new

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [58]:
# Multiply the ones array with the latest array
arr_ones * arr_ones_new

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [59]:
# Take the latest array to the power of 2 using '**'
arr_ones_new ** 2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
# Do the same thing with np.square()
np.square(arr_ones_new)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
# Find the mean of the latest array using np.mean()
np.mean(arr_ones_new)

1.0

In [62]:
# Find the maximum of the latest array using np.max()
np.max(arr_ones_new)

1.0

In [63]:
# Find the minimum of the latest array using np.min()
np.min(arr_ones_new)

1.0

In [64]:
# Find the standard deviation of the latest array
np.std(arr_ones_new)

0.0

In [65]:
# Find the variance of the latest array
np.var(arr_ones_new)

0.0

In [66]:
# Reshape the latest array to (3, 5, 1)
np.reshape(arr_ones_new, [3,5,1])

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [67]:
# Transpose the latest array
np.transpose(arr_ones_new)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What does the transpose do?

In [69]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_1 = np.random.randint(0,10,[3,3])
arr_2 = np.random.randint(0,10,[3,2])

In [70]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_1,arr_2)

array([[70, 53],
       [75, 76],
       [10,  4]])

In [71]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr_1 = np.random.randint(0,10,[4,3])
arr_2= np.random.randint(0,10,[4,3])

In [72]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_1,arr_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [73]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(arr_1,np.transpose(arr_2))

array([[57, 75, 30, 25],
       [16, 32,  0,  0],
       [32, 61, 14, 18],
       [ 8, 16,  0,  0]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [74]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr_1 = np.random.randint(0,10,[4,3])
arr_2 = np.random.randint(0,10,[4,3])

In [75]:
# Compare the two arrays with '>'
arr_1 > arr_2

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True,  True],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [76]:
# Compare the two arrays with '>='
arr_1 >= arr_2

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True, False]])

In [77]:
# Find which elements of the first array are greater than 7
arr_1 > 7

array([[False, False, False],
       [False,  True,  True],
       [False,  True, False],
       [False, False, False]])

In [78]:
# Which parts of each array are equal? (try using '==')
arr_1 == arr_2

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False, False]])

In [84]:
# Sort one of the arrays you just created in ascending order
np.sort(arr_1)

array([[0, 2, 6],
       [1, 8, 9],
       [2, 5, 9],
       [1, 7, 7]])

In [85]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr_1)

array([[1, 2, 0],
       [0, 1, 2],
       [2, 0, 1],
       [2, 0, 1]], dtype=int64)

In [86]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(arr_2)

3

In [87]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(arr_2)

6

In [88]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr_2, axis = 1)

array([1, 0, 1, 0], dtype=int64)

In [89]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr_2, axis = 0)

array([2, 1, 2], dtype=int64)

In [94]:
# Create an array of normally distributed random numbers
np.random.normal(0,1,10)

array([ 0.02393181,  0.87191399,  1.43735633,  0.00730637,  1.33088133,
        0.98820261,  0.23229616,  0.17618092, -1.15256537, -1.50076839])

In [96]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.